### ISSUE TITLE
Use name rather than project as Distribution attribute

### ISSUE THREAD

**Issue by pombredanne** [uranusjr/packaging-dists#5]
I would suggest to use `name` rather than `project` as Distribution attribute for the package name. This is the attribute used elsewhere as in the `packaging` library and  in pip.

**Comment by uranusjr** [comment]
The choice of `project` was an intentional choice since IMO `name` is ambigious to people less faimilar with Python packaging. We have *project name*, *package name*, *module name*, *distribution name* all mean slightly different things but sometimes used interchangably in some contexts, which can be extremely confusing.

Using `name` in `packaging.requirements` is fine since it is easy (to an extent) to understand it means *the name segment of a requirement*. But it does not work so well with `Wheel` and `SDist` since it may mean either file name or project name. `project` represents the variable’s meaning more clearly in this context.

**Comment by pombredanne** [comment]
Fair enough .... I am not convinced but I can live with this :)
